package nwsuaf.com.exam.entity.netmodel;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import nwsuaf.com.exam.entity.DaoSession;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "FANSWER".
*/
public class FAnswerDao extends AbstractDao<FAnswer, String> {

    public static final String TABLENAME = "FANSWER";

    /**
     * Properties of entity FAnswer.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, String.class, "id", true, "ID");
        public final static Property Ke = new Property(1, String.class, "ke", false, "KE");
        public final static Property Shu = new Property(2, String.class, "shu", false, "SHU");
        public final static Property Zhong = new Property(3, String.class, "zhong", false, "ZHONG");
    }


    public FAnswerDao(DaoConfig config) {
        super(config);
    }
    
    public FAnswerDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"FANSWER\" (" + //
                "\"ID\" TEXT PRIMARY KEY NOT NULL ," + // 0: id
                "\"KE\" TEXT," + // 1: ke
                "\"SHU\" TEXT," + // 2: shu
                "\"ZHONG\" TEXT);"); // 3: zhong
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"FANSWER\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, FAnswer entity) {
        stmt.clearBindings();
 
        String id = entity.getId();
        if (id != null) {
            stmt.bindString(1, id);
        }
 
        String ke = entity.getKe();
        if (ke != null) {
            stmt.bindString(2, ke);
        }
 
        String shu = entity.getShu();
        if (shu != null) {
            stmt.bindString(3, shu);
        }
 
        String zhong = entity.getZhong();
        if (zhong != null) {
            stmt.bindString(4, zhong);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, FAnswer entity) {
        stmt.clearBindings();
 
        String id = entity.getId();
        if (id != null) {
            stmt.bindString(1, id);
        }
 
        String ke = entity.getKe();
        if (ke != null) {
            stmt.bindString(2, ke);
        }
 
        String shu = entity.getShu();
        if (shu != null) {
            stmt.bindString(3, shu);
        }
 
        String zhong = entity.getZhong();
        if (zhong != null) {
            stmt.bindString(4, zhong);
        }
    }

    @Override
    public String readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0);
    }    

    @Override
    public FAnswer readEntity(Cursor cursor, int offset) {
        FAnswer entity = new FAnswer( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // ke
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // shu
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3) // zhong
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, FAnswer entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setKe(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setShu(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setZhong(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
     }
    
    @Override
    protected final String updateKeyAfterInsert(FAnswer entity, long rowId) {
        return entity.getId();
    }
    
    @Override
    public String getKey(FAnswer entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(FAnswer entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
